name: web

permissions:
  contents: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

on:
  pull_request:
    paths:
      - 'web/**'
    types: [opened, synchronize, reopened, closed]
  push:
    paths:
      - 'web/**'
    branches:
      - master
  workflow_dispatch:

jobs:
  web:
    name: web
    if: github.repository == 'riverar/windows-rs'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: current

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '23.1' # Temporary: https://github.com/nodejs/node/issues/55826

      # Features

      - name: Build features site
        working-directory: current/web/features
        run: |
          npm ci
          npm run build

      # /Features

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Update gh-pages
        run: |
          cd gh-pages
          
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            if [ "${{ github.event.action }}" == "closed" ]; then
              rm -rf features/preview/pr-${{ github.event.number }}
            else
              mkdir -p features/preview/pr-${{ github.event.number }}
              rm -rf features/preview/pr-${{ github.event.number }}/*
              cp -r ../current/web/features/build/* features/preview/pr-${{ github.event.number }}/
            fi
          fi

          if [ "${{ github.ref }}" == "refs/heads/master" ]; then
            mkdir -p features
            rm -rf features/*
            cp -r ../current/web/features/build/* features/
          fi

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update from ${{ github.sha }}" && git push)
